### ISSUE TITLE
Please allow a user to click the text on a Skittle

### ISSUE THREAD

**Issue by kamilski81** [aashrairavooru/Skittles#10]
Currently only the buttons are clickable.  thanks!

**Comment by ghost** [comment]
Okay assuming you are already aware of how the click listeners work in this library, this is the difference for textSkittle

```
@Override public void onTextSkittleClick(TextSkittle textSkittle, String type) {}
```

the type can be of two type:
- skittle
- text
  so when you click on the **skittle** itself the listener will be called with type as skittle and when you click the text the listener will be called with the type as **text**

**Comment by ghost** [comment]
I will be doing a release on this pretty soon Cheers :)

**Comment by ghost** [comment]
You can now use this in the new version

```
dependencies{
compile 'com.rlj.library:skittles:2.1.0'
}
```
