### ISSUE TITLE
Make the Skittle Container a Recycler View

### ISSUE THREAD

**Issue by ghost** [aashrairavooru/Skittles#15]
Currently the skittle container is a linear layout which does its job but makes things such as **spacing** and **animations** a pain, if we want to make the library more customizable **recycler view** is the way to go,

**Comment by polok** [comment]
Hi @aashrairavooru,

I applied different approach when working on [issue](https://github.com/aashrairavooru/Skittles/issues/9). Please, have a look. Of course I don't see a problem to think about another approach in the future

**Comment by ghost** [comment]
Done with 3.0.0
