### ISSUE TITLE
Layout issues with TextSkittle 

### ISSUE THREAD

**Issue by ligi** [aashrairavooru/Skittles#18]
Icon-Only skittles work fine but when using one with text there are 2 problems:

![skittles_problem](https://cloud.githubusercontent.com/assets/111600/12704692/80e315d0-c860-11e5-9378-30fa60b00850.png)

a) the shadow is cropped
b) the text is not centered vertically

with this code:

``` java
  final SkittleBuilder builder = new SkittleBuilder.Builder(this, fam)
                .mainSkittleColor( R.color.accent)
                .build();


        builder.makeTextSkittle("foo",R.drawable.ic_action_bulb).add();
```

**Comment by ghost** [comment]
Noted

**Comment by ghost** [comment]
Checkout the new version 3.0.0 it fixes everything, NOTE: the new version has breaking changes refer to the readme for the changes or feel free to raise an issue

**Comment by ligi** [comment]
having a problem using 3.0.0:

```
* What went wrong:
A problem occurred configuring project ':mobile'.
> Could not resolve all dependencies for configuration ':mobile:_debugCompile'.
   > Could not resolve com.rlj.library:skittles:3.0.0.
     Required by:
         VaporizerControl:mobile:unspecified
      > Could not resolve com.rlj.library:skittles:3.0.0.
         > inconsistent module metadata found. Descriptor: com.rlj.library:skittles:3.0.0-SNAPSHOT Errors: bad version: expected='3.0.0' found='3.0.0-SNAPSHOT'


```

**Comment by ghost** [comment]
Hmm seems like the artifact wasn't published correctly I have uploaded a new version 4.0.0, I tested it should work correctly thanks for your patiece

**Comment by ligi** [comment]
Looks better now - but why did you jump a whole major for this ?-)
