### ISSUE TITLE
Skittles are squished toghether (no margins?)

### ISSUE THREAD

**Issue by leoncvlt** [aashrairavooru/Skittles#3]
On MotoE 5.1. is that because the fab_margins values in Skittles/skittles/src/main/res/values/dimens.xml are set to 0.1?

**Comment by ghost** [comment]
Yeah this was a problem with lollipop,i have fixed it see #1 will be doing a release in an hour or so.check the values-21 file,they handle the margins for lollipop+.
- For pre-lollipop devices the FloatingActionButton adds its own margins and padding
- The 0.1 padding in values is for snackbar support in pre-lollipop devices,its a bug in FloatingActionButton

**Comment by ghost** [comment]
Hey the latest release fixes this issue,check it out,use

```
compile 'com.rlj.library:skittles:1.0.0'
```

in your dependencies

**Comment by leoncvlt** [comment]
Yup just tested this, works fine now.
