### ISSUE TITLE
CloseMenu() method?

### ISSUE THREAD

**Issue by leoncvlt** [aashrairavooru/Skittles#7]
Hi, it's me again.
I have noticed that when I launch an acitvity from a skittle and then go back, the menu is still open. Would be useful to have a way to force the menu to close.

**Comment by ghost** [comment]
Its surely one of the things I wanted to do, I think a method in
skittlebuilder for toggling this behavior should do i guess

**Comment by ghost** [comment]
added the method toggleSkittleMenu() in SkittleBuilder checkout 8fa0da323a746d343a4b9aab3ba93d76e6b64cc7

**Comment by ghost** [comment]
Give it a spin in the new version

```
compile 'com.rlj.library:skittles:1.0.2'
```

**Comment by haideralipunjabi** [comment]
Can we do this in
    `com.rlj.library:skittles:4.1.1`
