### ISSUE TITLE
how to import builder?

### ISSUE THREAD

**Issue by persiansushiant** [aashrairavooru/Skittles#8]
i cant find how to import builder in your sample app
android studio doesnt recognize this 
 skittleBuilder = new SkittleBuilder.Builder(this, skittleLayout)
                .mainSkittleColor(Color.GREEN)
                .mainSkittleIcon(R.drawable.ic_android_white_18dp)
                .build();

**Comment by ghost** [comment]
Use the latest version

```
compile 'com.rlj.library:skittles:2.0.0
```

Sorry forgot to update the readme for the same
