### ISSUE TITLE
Dim the screen when click on skittle ?

### ISSUE THREAD

**Issue by devabir93** [aashrairavooru/Skittles#9]

**Comment by ghost** [comment]
Hmm yeah a needed feature, might take me some time to do this, bit busy, pull request welcome

**Comment by devabir93** [comment]
waitin.. :D

**Comment by polok** [comment]
Just to let you know that I am working on this feature and PR should be ready on Sunday ;)

**Comment by ghost** [comment]
@polok hey take a look at #15 I think it needs to be done and this issue can be easily completed afterwards, lets move the discussion there

**Comment by ghost** [comment]
@polok take a look at the new version 4.0.0 or in the master branch, the api has been changed and is now backed by **RecyclerView**, If you are interested you can open a new pull request with these changes with respect to the new api

**Comment by polok** [comment]
@aashrairavooru Thanks for letting me know. I will have a look for sure but don't know exactly when, quite many things to do in my to-do list for now :/

**Comment by ghost** [comment]
NP man, would love feedback on the rewritten api as well

**Comment by ghost** [comment]
@polok best if you make a pull on the dev branch I might push some changes before you make your pull request on sunday

**Comment by polok** [comment]
@aashrairavooru I made a quick look on your latest changes. They are really cool, there was a good idea to use recyclerview. Next week I will adopt these changes to my implementation of 'shadow' effect and I will prepare PR.

**Comment by ghost** [comment]
Thanks man, looking forward to it
